# Laravel Cloud Configuration
# https://cloud.laravel.com

# Environment (production/staging)
environment: production

# PHP Version
php: 8.3

# Build Commands
build:
  - composer install --no-dev --optimize-autoloader
  - npm ci && npm run build
  - mkdir -p storage/app/public
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan filament:optimize

# Deployment Commands (run after build)
deploy:
  - php artisan migrate --force
  - php artisan queue:restart
  - php artisan cache:clear

# Cron Jobs (Laravel Scheduler)
cron:
  - schedule: "* * * * *"
    command: "php artisan schedule:run"

# Queue Workers
queues:
  - connection: database
    queue: default
    processes: 2
    tries: 3
    timeout: 90
    sleep: 3

# Health Check
health:
  path: /
  timeout: 10

# Environment Variables (set in Laravel Cloud dashboard)
# Required:
# - APP_KEY (generate with: php artisan key:generate --show)
# - APP_URL (your production URL)
# - DB_CONNECTION=mysql
# - DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD
# - MAIL_MAILER, MAIL_HOST, MAIL_PORT, MAIL_USERNAME, MAIL_PASSWORD
# - FONNTE_API_KEY (for WhatsApp notifications)
# - QUEUE_CONNECTION=database
