# Laravel Cloud Configuration
# https://cloud.laravel.com

# Environment (production/staging)
environment: production

# PHP Version
php: 8.3

# Build Commands
build:
  - composer install --no-dev --optimize-autoloader
  - npm ci && npm run build
  - mkdir -p storage/app/public/lapangan-images
  - mkdir -p storage/app/public/payment-proofs
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan filament:optimize

# Deployment Commands (run after build)
deploy:
  - php artisan migrate --force
  - php artisan config:clear
  - php artisan cache:clear
  - php artisan view:clear
  - php artisan queue:restart
  - php artisan storage:link

# Persistent Storage (IMPORTANT: Files won't be deleted on redeploy)
storage:
  - storage/app/public


# Cron Jobs (Laravel Scheduler)
cron:
  - schedule: "* * * * *"
    command: "php artisan schedule:run"

# Queue Workers
queues:
  - connection: database
    queue: default
    processes: 2
    tries: 3
    timeout: 90
    sleep: 3

# Health Check
health:
  path: /
  timeout: 10
